id: P006603
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 12:09:43.715888
source_metadata:
  id: bdr:W1KG17193
  title: དཔལ་ས་སྐྱའི་ཕྱག་སྲོལ་རྒྱུན་མཁོའི་ཆོས་སྤྱོད་ཀྱི་རིམ་པ་ངོ་མཚར་མེ་ཏོག་འཕྲེང་བ།
  author: ''
  volumes:
    4051c1a22be84f738962c5d7554dc161:
      image_group_id: I1KG17553
      title: ''
      volume_number: 1
      total_pages: 206
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
